name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Service 1 image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/service1:latest ./services/service1
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/service1:latest

    - name: Build and push Service 2 image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/service2:latest ./services/service2
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/service2:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes cluster
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
